version: '3.5'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  chat:
    build: .
    container_name: chat
    image: chat
    ports:
      - "8080:8080"
    depends_on:
      - redis
