version: '3.5'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  chat:
    build: .
    container_name: chat
    image: chat
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - redis
